name: PlusEnchantment
version: '${version}'
main: com.github.majisyou.plusenchantment.PlusEnchantment
api-version: 1.18
authors: [ majisyou ]
description: add limit break enchant, add scrap system, add custom enchant

commands:
  test:
    description: commandtest用
    usage: 原因不明の失敗
    permission: PE.OP

  DebugEnchant:
    description: debug
    usage: whhieee
    permission: PE.OP

  PlusEnchant_reloadConfig:
    description: config-reload
    usage: whiiii
    permission: PE.OP

  ChangeItem:
    description: redshirt
    usage: コマンド失敗
    permission: PE.user